version: '3.8'

networks:
  macvlan_ipxe:
    name: macvlan_ipxe
    driver: macvlan
    driver_opts:
      parent: ${MACVLAN_IPXE_PARENT_INTERFACE}
    external: false
    ipam:
      config:
        - subnet: ${MACVLAN_IPXE_SUBNET}
          ip_range: ${MACVLAN_IPXE_IP_RANGE}
          gateway: ${MACVLAN_IPXE_GATEWAY}

services:
  ipex-server-core:
    container_name: ipxe-server-core
    image: "tsutomu/ipxe-server-core:${TAG_IPXE_SERVER_CORE}"
    privileged: true
    networks:
      macvlan_ipxe:
        ipv4_address: ${IP_TFTP_NEXT_SERVER}
    command: ${COMMAND_IPXE_SERVER_CORE}
    environment:
      - IP_TFTP_NEXT_SERVER=${IP_TFTP_NEXT_SERVER}
      - IP_HTTP_NEXT_SERVER=${IP_HTTP_NEXT_SERVER}

  ipxe-image-server:
    container_name: ipxe-image-server
    image: "tsutomu/ipxe-image-server:${TAG_IPXE_SERVER_CORE}"
    networks:
      macvlan_ipxe:
        ipv4_address: ${IP_HTTP_NEXT_SERVER}
    volumes:
      - ./os/images:/var/www/os/images

