version: '3.8'

networks:
  macvlan_ipxe:
    name: macvlan_ipxe
    driver: macvlan
    external: true
    ipam:
      config:
        - subnet: "172.31.0.0/16"
          ip_range: "172.31.2.128/25"
          gateway: "172.31.0.1"

services:
  ipex-server-core:
    container_name: ipxe-server-core
    image: tsutomu/ipxe-server-core:${TAG_IPXE_SERVER_CORE}
    privileged: true
    networks:
      macvlan_ipxe:
        ipv4_addresses: "172.31.2.11"
    command: [${COMMAND_IPXE_SERVER_CORE}]

  ipxe-image-server:
    container_name: ipxe-image-server
    image: tsutomu/ipxe-server-core:${TAG_IPXE_SERVER_CORE}
    networks:
      macvlan_ipxe:
        ipv4_addresses: "172.31.2.12"

