# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: rlespinasse/drawio-export:v4.15.0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Check out the repo2
        uses: actions/checkout@v3
        with:
          repository: TsutomuNakamura/references.git
          path: references

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          # Generate dbus-daemon
          dbus-uuidgen > /var/lib/dbus/machine-id
          mkdir -p /var/run/dbus
          dbus-daemon --config-file=/usr/share/dbus-1/system.conf --print-address

          # Export draw-io-files with generating display
          cd drawio
          xvfb-run --auto-servernum --server-num=1 --server-args='-screen 0, 1920x1080x24' /opt/drawio-exporter/drawio-exporter --drawio-desktop-headless
          find . -maxdepth 5

